In [1]:
import numpy as np
a = np.array([[2,3]])
print(a)
b = np.where(a==2,4,a)
print(b)

[[2 3]]
[[4 3]]


In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

df = pd.read_csv("features.csv")
print(df.head())
#converty yn to 01 and site nonsite to 10
a = df.to_numpy()
print(a[0,4:5])
a1 = np.where(a=='y',1,a)
a2 = np.where(a1=='n',0,a1)
a3 = np.where(a2=='nonsite',0,a2)
a4 = np.where(a3=='site',1,a3)
print(a1.shape,a2.shape,a3.shape,a4.shape,)
print("a2:",a2[0:4,99:101])
print("a4:",a4[0:4,99:101])

X=a4[:,0:100]
y = a4[:,100:101]

print("X:",X[0:4])
print("y:",y[0:4])
print("before reshape:",X.shape,y.shape)
#y = y.reshape(y.shape[1],y.shape[0])
#print("after reshape:",X.shape,y.shape)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=1115)
print(X_train.shape, X_test.shape,y_train.shape,y_test.shape)


  ALA0 ALA1 ALA2 ALA3 ALA4 ARG0 ARG1 ARG2 ARG3 ARG4  ... TYR1 TYR2 TYR3 TYR4  \
0    n    n    n    n    y    n    n    n    n    n  ...    n    n    n    y   
1    n    n    n    y    n    n    n    n    n    n  ...    n    n    n    n   
2    n    n    n    n    y    n    n    n    y    y  ...    n    n    n    n   
3    n    n    n    n    n    n    n    n    n    n  ...    n    y    y    n   
4    n    n    n    n    n    n    n    n    n    n  ...    n    n    n    n   

  VAL0 VAL1 VAL2 VAL3 VAL4     SITE  
0    n    n    n    y    n  nonsite  
1    n    n    y    n    n     site  
2    n    n    n    n    y  nonsite  
3    n    n    n    n    y  nonsite  
4    n    n    n    n    n     site  

[5 rows x 101 columns]
['y']
(94, 101) (94, 101) (94, 101) (94, 101)
a2: [[0 'nonsite']
 [0 'site']
 [1 'nonsite']
 [1 'nonsite']]
a4: [[0 0]
 [0 1]
 [1 0]
 [1 0]]
X: [[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0
  1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0

In [3]:
#print(y_train)

In [4]:
#print(y_train.ravel())

In [5]:
print("y_test before:",y_test)
y_test=y_test.ravel()
y_test=y_test.astype('int')
print("y_test after ravel and int cast",y_test)

y_test before: [[0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]]
y_test after ravel and int cast [0 0 1 0 1 0 0 1 0 1 0 0 1 1 1 1 0 0 0]


In [6]:
model = GaussianNB()
y_train=y_train.ravel()
y_train=y_train.astype('int')
model.fit(X_train,y_train)

y_pred = model.predict(X_test)
print("y_pred shape:",y_pred.shape," y_test shape:",y_test.shape)
print("y_pred",y_pred)
#, fn, tp
tn, fp = confusion_matrix(y_test, y_pred)
print(tn,fp)

y_pred shape: (19,)  y_test shape: (19,)
y_pred [0 0 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1]
[4 7] [0 8]


In [8]:
y_test = [0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0]
y_pred=  [0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1]
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print(tn, fp, fn, tp)

4 7 0 8


In [11]:
from sklearn.feature_selection import mutual_info_classif


foo = mutual_info_classif(X_train,y_train,discrete_features=True,n_neighbors=3, copy=True,random_state=1115)


In [13]:
print(foo.shape)

(100,)


In [18]:
print(foo)
print(max(foo))
print(sorted(foo))

[-1.66533454e-16  1.28125178e-02  5.72928532e-03  4.28921648e-03
  9.46778674e-04 -1.66533454e-16 -1.66533454e-16  2.54564138e-04
  1.13964167e-02  8.16406346e-02 -1.66533454e-16  2.59211417e-02
  2.54564138e-04  2.76742824e-01  6.63538413e-03 -1.66533454e-16
  1.28125178e-02  2.57773443e-01  3.63205866e-01  1.16049488e-03
 -1.66533454e-16 -1.66533454e-16 -1.66533454e-16 -1.66533454e-16
  1.28125178e-02 -1.66533454e-16  3.93410515e-02  5.72928532e-03
  9.91986875e-03  6.63538413e-03  1.28125178e-02  2.59211417e-02
  6.57465892e-03  1.61154051e-02  2.38737796e-01 -1.66533454e-16
  5.30887173e-02  1.48805986e-03  2.58642777e-01  4.07503362e-03
 -1.66533454e-16 -1.66533454e-16  2.66704741e-05  6.57465892e-03
  5.30887173e-02 -1.66533454e-16  1.28125178e-02  1.14348040e-01
  5.09363545e-03  1.38734761e-02 -1.66533454e-16  3.93410515e-02
  8.31638291e-04  3.11099812e-02  3.10097046e-02 -1.66533454e-16
  1.28125178e-02  2.29552336e-03  4.72947643e-02  8.89464059e-02
 -1.66533454e-16  1.28125

In [20]:
print(y_train)

[1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 1 1 1 1 0 1 1 0
 0 0 1 1 1 1 1 1 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 1 1 0 0 0 1 0 1
 1]


In [22]:
print(np.where(foo == 0.3632058664604266))
print(np.where(foo == 0.27674282390529337))
print(np.where(foo == 0.25864277687768666 ))
print(np.where(foo == 0.2577734425071343 ))
print(np.where(foo == 0.23873779611518275))
 

(array([18]),)
(array([13]),)
(array([38]),)
(array([17]),)
(array([34]),)


In [30]:
df.iloc[0:,0:20]

ALA0 ALA1 ALA2 ALA3 ALA4 ARG0 ARG1 ARG2 ARG3 ARG4 ASN0 ASN1 ASN2 ASN3 ASN4  \
0     n    n    n    n    y    n    n    n    n    n    n    n    n    n    n   
1     n    n    n    y    n    n    n    n    n    n    n    n    n    y    n   
2     n    n    n    n    y    n    n    n    y    y    n    n    n    n    n   
3     n    n    n    n    n    n    n    n    n    n    n    n    n    n    n   
4     n    n    n    n    n    n    n    n    n    n    n    n    n    y    n   
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
89    n    n    n    n    n    n    n    n    n    n    n    n    n    n    y   
90    n    n    n    y    n    n    n    n    n    n    n    n    y    n    n   
91    n    n    n    n    n    n    n    n    n    n    n    n    n    y    n   
92    n    n    n    n    n    n    n    n    n    n    n    n    n    y    n   
93    n    n    n    y    n    n    n    n    n    n    n    n    n    y    n   

   ASP0 ASP1 ASP2 ASP3 ASP4  
0     n    n    n    n    n  
1     n    n    y    y    n  
2     n    n    n    n    y  
3     n    n    n    n    n  
4     n    n    y    y    n  
..  ...  ...  ...  ...  ...  
89    n    n    n    n    n  
90    n    n    y    y    n  
91    n    n    y    y    n  
92    n    n    y    y    n  
93    n    n    y    y    n  

[94 rows x 20 columns]

In [29]:
df.iloc[:,13:14]


ASN3
0     n
1     y
2     n
3     n
4     y
..  ...
89    n
90    n
91    y
92    y
93    y

[94 rows x 1 columns]

In [31]:
df.iloc[:,17:18]

ASP2
0     n
1     y
2     n
3     n
4     y
..  ...
89    n
90    y
91    y
92    y
93    y

[94 rows x 1 columns]

In [32]:
df.iloc[:,18:19]

ASP3
0     n
1     y
2     n
3     n
4     y
..  ...
89    n
90    y
91    y
92    y
93    y

[94 rows x 1 columns]

In [33]:
df.iloc[:,34:35]

GLU4
0     n
1     y
2     n
3     n
4     y
..  ...
89    y
90    y
91    y
92    y
93    y

[94 rows x 1 columns]

In [34]:
df.iloc[:,38:39]

GLY3
0     n
1     n
2     n
3     n
4     y
..  ...
89    n
90    y
91    y
92    y
93    y

[94 rows x 1 columns]

In [74]:
df_casites = pd.read_csv("CAsites.txt",header=None,sep="\t")
print(df_casites.head())
print(df_casites.iloc[0:2,:])
print("-------")
print(df_casites.iloc[:,1:2])

#print(df_casites.iloc[0:2,1:2].to_numpy()[0][0].split()[0])
#print(df_casites.iloc[0:10,1:2].to_numpy()[0][0].split()[0])
print(df_casites.iloc[35:36,:])

          0                         1
0  1BJF.pdb    16.721  -2.444   2.658
1  1BJF.pdb    13.212  19.485   6.979
2  1BJF.pdb     4.039  27.117   4.877
3  1BJF.pdb    21.650   8.826  10.743
4  1BJF.pdb     2.469  -0.099   3.157
          0                         1
0  1BJF.pdb    16.721  -2.444   2.658
1  1BJF.pdb    13.212  19.485   6.979
-------
                           1
0     16.721  -2.444   2.658
1     13.212  19.485   6.979
2      4.039  27.117   4.877
3     21.650   8.826  10.743
4      2.469  -0.099   3.157
5     -8.859   3.869   2.087
6      1.708  47.776  24.197
7     -2.112  44.438  13.360
8     30.463  11.962  10.473
9     29.181  17.963   0.804
10     6.148  12.467  15.730
11    -4.326  11.224  11.038
12    -1.864  36.835 -15.092
13    -9.907  28.661 -12.932
14    46.224   7.128  -8.698
15    36.763  12.606  -4.815
16    22.026 -16.616  21.879
17    32.674 -10.435  -5.410
18    31.568 -19.422  27.202
19     5.700   5.700  34.320
20    35.060  22.261  26.252
21     9.863