In [ ]:
#notes: pick markdown cell type
#to insert image use <img src='test.png'> and click the run cell then the image is loaded

<img src='w2_1.png'>

ANS: LPF

<img src="w2_2.png">

[-1 -1 -1; -1 9 -1; -1 -1 -1] is the HPF

<img src='w2_3.png'>

In [13]:
import numpy as np
from scipy import signal
from scipy import misc

x=np.matrix([[1, 2, 3 ], [0, 4, 5], [0, 0, 6]])
y=np.matrix([[1, 1], [1, 1]])

z=signal.convolve2d(x,y)
print z

[[ 1  3  5  3]
 [ 1  7 14  8]
 [ 0  4 15 11]
 [ 0  0  6  6]]


<img src='w2_4.png'>

True

<img src='w2_5.png'>

The first one is true; assuming the input follows superposition and scaling
Second one is false
Third is false b/c y=x**h and if x is 0 then y is 0 regardless of h
Fourth is false b/c y=x**h. If y(n1,n2)=0 then h(s)=0 or null function then y is always 0 regardless of x. 

<img src='w2_6.png'>

In [19]:
#This is tricky, use a test case. 
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
y=np.matrix([[1,1],[1,1]])

#x size =3x3; y size=[2x2] P1-1=3, P2-1=2, P1=4, P2=3

#The convolution of x**y: 
z=signal.convolve2d(x,y)
print z

#the Z size is 4x4 so the areas outside this are 0
#the minimum is x dimension is 5 and y dimension is 5
#P1=4, P2=3, P1+P2-2=7-2=5 so answer is last choice above 


[[ 1  3  5  3]
 [ 5 12 16  9]
 [11 24 28 15]
 [ 7 15 17  9]]


<img src='w2_7.png'>

In [11]:
from matplotlib import pyplot as plt
import numpy as np
import scipy.misc
from scipy import signal

f = scipy.misc.imread('/Users/dc/TestCode/TestMatlab/computervision/updownsample.jpg')
print np.shape(f)
#plt.imshow(f)
#displays in another window
#plt.show()

img = f.astype(np.double)
print "%f" % f[0,0]

lpf=np.matrix([[1/9.,1/9.,1/9.],[1/9.,1/9.,1/9.],[1/9.,1/9.,1/9.]])
print lpf
z=signal.convolve2d(f,lpf,mode='same')
print z[0,0]

n=np.shape(z)
print  n
#the instructions may be incorrect, 255 is for gray scale but we converted to double
diff = np.subtract(f,z)
print diff[0,0]
diff_squared = np.square(diff)
print np.shape(diff_squared)

MSE = (np.sum(diff_squared))*1/(n[0]*n[1])
print 10*np.log10(255/MSE)



(359, 479)
120.000000
[[ 0.11111111  0.11111111  0.11111111]
 [ 0.11111111  0.11111111  0.11111111]
 [ 0.11111111  0.11111111  0.11111111]]
53.8888888889
(359, 479)
66.1111111111
(359, 479)
28.1492628127


<img src='w2_8.png'>

In [28]:
from matplotlib import pyplot as plt
import numpy as np
import scipy.misc
from scipy import signal

f = scipy.misc.imread('/Users/dc/TestCode/TestMatlab/computervision/lena.gif').astype(np.double)
plt.imshow(f)
plt.show()
print f[0,0]

lpf=np.matrix([[1/9.,1/9.,1/9.,1/9.,1/9.],[1/9.,1/9.,1/9.,1/9.,1/9.],
               [1/9.,1/9.,1/9.,1/9.,1/9.],[1/9.,1/9.,1/9.,1/9.,1/9.],
               [1/9.,1/9.,1/9.,1/9.,1/9.]])

f_shape=np.shape(f)
lpf_shape = np.shape(lpf)
print 'f_shape:%d %d' % f_shape
print 'lpf_shape:%d %d' % lpf_shape
z=signal.convolve2d(f,lpf,mode='same')
diff = np.subtract(f,z)
print diff[0,0]
diff_squared = np.square(diff)
print diff_squared
print np.shape(diff_squared)

MSE = (np.sum(diff_squared))*1/(f_shape[0]*f_shape[1])
print 'MSE:%f' % MSE
print 10*np.log10(255.0*255.0/MSE)

137.0
f_shape:256 256
lpf_shape:5 5
1.77777777778
[[  3.16049383e+00   1.96544444e+03   8.66967901e+03 ...,   3.01279012e+03
    4.41000000e+02   2.18382716e+02]
 [  1.81097531e+03   1.06319012e+04   2.78148272e+04 ...,   8.30123457e+03
    2.14677778e+03   9.40444444e+02]
 [  7.24390123e+03   2.69324568e+04   5.69087531e+04 ...,   1.55140864e+04
    6.74223457e+03   4.25393827e+03]
 ..., 
 [  2.81493827e+02   1.00277778e+03   2.42282716e+03 ...,   7.47264198e+03
    3.01279012e+03   1.18641975e+03]
 [  2.21679012e+02   4.79123457e+02   1.27211111e+03 ...,   3.26167901e+03
    1.05986420e+03   2.52456790e+02]
 [  1.51234568e+01   2.39012346e+01   4.22530864e+02 ...,   6.81790123e+02
    1.99123457e+02   5.21604938e+01]]
(256, 256)
MSE:37286.302770
2.41531039088
