In [55]:
#1 softmax


scores = [3.0, 1.0, 0.2]

import numpy as np

#input list or 1d array
#output softmax as list or 1d array
def softmax_one(x):
    """Compute softmax values for each sets of scores in x."""
    returnMe = np.array([],np.double)
    sum = np.sum([np.exp(val) for val in x])
    #print 'sum:', sum
    result = [np.exp(val)/sum for val in x]
    return np.array(result)

print(softmax_one(scores))

# Plot softmax curves
import matplotlib.pyplot as plt
x = np.arange(-2.0, 6.0, 0.1)
scores = np.vstack([x, np.ones_like(x), 0.2 * np.ones_like(x)])

plt.plot(x, softmax_one(scores).T, linewidth=2)
plt.show()


[ 0.8360188   0.11314284  0.05083836]


In [58]:
import numpy as np
#the case above fails for a 2d array
scores = np.array([[1, 2, 3, 6],
                   [2, 4, 5, 6],
                   [3, 8, 7, 6]])

#scores = [3.0, 1.0, 0.2]

def softmax(scores):
    z=np.array(scores)
    if z.ndim==1:
        return softmax_one(scores)
    
    s = scores.shape

    print "numColumns:", s[1]
    if s[1] ==0:
        return softmax_one(scores)

    arrs = []
    for colIndex in range(0,s[1]):
        temp = scores[:,colIndex]
        print "colIndex:",colIndex, "col:",scores[:,colIndex]
        print "softmax:",softmax_one(temp)
        arrs.append(softmax_one(temp))
    print "arrs:", arrs

    result=(arrs[0])
    print "result:",result
    for x in range(1,len(arrs)):
        print "processing x:", x, 'arr[x]', arrs[x]
        result = np.column_stack((result,arrs[x]))
    print "result:", result

    
softmax(scores)


numColumns: 4
colIndex: 0 col: [1 2 3]
softmax: [ 0.09003057  0.24472847  0.66524096]
colIndex: 1 col: [2 4 8]
softmax: [ 0.00242826  0.01794253  0.97962921]
colIndex: 2 col: [3 5 7]
softmax: [ 0.01587624  0.11731043  0.86681333]
colIndex: 3 col: [6 6 6]
softmax: [ 0.33333333  0.33333333  0.33333333]
arrs: [array([ 0.09003057,  0.24472847,  0.66524096]), array([ 0.00242826,  0.01794253,  0.97962921]), array([ 0.01587624,  0.11731043,  0.86681333]), array([ 0.33333333,  0.33333333,  0.33333333])]
result: [ 0.09003057  0.24472847  0.66524096]
processing x: 1 arr[x] [ 0.00242826  0.01794253  0.97962921]
processing x: 2 arr[x] [ 0.01587624  0.11731043  0.86681333]
processing x: 3 arr[x] [ 0.33333333  0.33333333  0.33333333]
result: [[ 0.09003057  0.00242826  0.01587624  0.33333333]
 [ 0.24472847  0.01794253  0.11731043  0.33333333]
 [ 0.66524096  0.97962921  0.86681333  0.33333333]]


In [ ]:
scores = np.array([[1, 2, 3, 6],
                   [2, 4, 5, 6],
                   [3, 8, 7, 6]])

[[ 0.09003057  0.00242826  0.01587624  0.33333333]
 [ 0.24472847  0.01794253  0.11731043  0.33333333]
 [ 0.66524096  0.97962921  0.86681333  0.33333333]]