In [ ]:
#notes: pick markdown cell type
#to insert image use <img src='test.png'> and click the run cell then the image is loaded

<img src='w2_1.png'>

ANS: LPF

<img src="w2_2.png">

[-1 -1 -1; -1 9 -1; -1 -1 -1] is the HPF

<img src='w2_3.png'>

In [13]:
import numpy as np
from scipy import signal
from scipy import misc

x=np.matrix([[1, 2, 3 ], [0, 4, 5], [0, 0, 6]])
y=np.matrix([[1, 1], [1, 1]])

z=signal.convolve2d(x,y)
print z

[[ 1  3  5  3]
 [ 1  7 14  8]
 [ 0  4 15 11]
 [ 0  0  6  6]]


<img src='w2_4.png'>

True

<img src='w2_5.png'>

The first one is true; assuming the input follows superposition and scaling
Second one is false
Third is false b/c y=x**h and if x is 0 then y is 0 regardless of h
Fourth is false b/c y=x**h. If y(n1,n2)=0 then h(s)=0 or null function then y is always 0 regardless of x. 

<img src='w2_6.png'>

In [19]:
#This is tricky, use a test case. 
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
y=np.matrix([[1,1],[1,1]])

#x size =3x3; y size=[2x2] P1-1=3, P2-1=2, P1=4, P2=3

#The convolution of x**y: 
z=signal.convolve2d(x,y)
print z

#the Z size is 4x4 so the areas outside this are 0
#the minimum is x dimension is 5 and y dimension is 5
#P1=4, P2=3, P1+P2-2=7-2=5 so answer is last choice above 


[[ 1  3  5  3]
 [ 5 12 16  9]
 [11 24 28 15]
 [ 7 15 17  9]]


<img src='w2_7.png'>

In [11]:
from matplotlib import pyplot as plt
import numpy as np
import scipy.misc
from scipy import signal

f = scipy.misc.imread('/Users/dc/TestCode/TestMatlab/computervision/updownsample.jpg')
print np.shape(f)
#plt.imshow(f)
#displays in another window
#plt.show()

img = f.astype(np.double)
print "%f" % f[0,0]

lpf=np.matrix([[1/9.,1/9.,1/9.],[1/9.,1/9.,1/9.],[1/9.,1/9.,1/9.]])
print lpf
z=signal.convolve2d(f,lpf,mode='same')
print z[0,0]

n=np.shape(z)
print  n
#the instructions may be incorrect, 255 is for gray scale but we converted to double
diff = np.subtract(f,z)
print diff[0,0]
diff_squared = np.square(diff)
print np.shape(diff_squared)

MSE = (np.sum(diff))*1/(n[0]*n[1])
print 10*np.log10(255/MSE)



(359, 479)
120.000000
[[ 0.11111111  0.11111111  0.11111111]
 [ 0.11111111  0.11111111  0.11111111]
 [ 0.11111111  0.11111111  0.11111111]]
53.8888888889
(359, 479)
66.1111111111
(359, 479)
28.1492628127
